-- ============================================================================
-- schema_postgres.sql — Postgres (Neon) schema for the multi-sport platform.
--
-- Apply this once to a fresh Neon project (see PLATFORM_HANDOFF.md / the
-- schema-rebuild plan — old MLB data lives in a separate, untouched Neon
-- project and is not migrated here).
--
-- SQLite -> Postgres mapping decisions (mirrors scripts/database.py init_db()):
--   INTEGER PRIMARY KEY AUTOINCREMENT  -> INTEGER GENERATED BY DEFAULT AS IDENTITY
--        (BY DEFAULT, not ALWAYS, so ad-hoc inserts with explicit ids stay legal.)
--   REAL                               -> DOUBLE PRECISION
--   TEXT                               -> TEXT
--   Boolean-ish INTEGER columns (is_shadow, is_fade, success) are kept as
--        INTEGER on purpose — no BOOLEAN coercion, matches SQLite exactly.
--   Date/datetime values stay TEXT, byte-identical to SQLite (no reformatting).
-- ============================================================================

CREATE TABLE sports (
    sport        TEXT PRIMARY KEY,
    display_name TEXT,
    active       INTEGER DEFAULT 1
);
INSERT INTO sports (sport, display_name, active) VALUES ('nfl', 'NFL', 1);

CREATE TABLE games (
    game_id     TEXT PRIMARY KEY,
    sport       TEXT NOT NULL REFERENCES sports(sport),
    season      INTEGER,
    week        INTEGER,
    game_date   TEXT,
    start_utc   TEXT,
    home_team   TEXT,
    away_team   TEXT,
    venue       TEXT,
    status      TEXT,
    home_score  INTEGER,
    away_score  INTEGER,
    updated_utc TEXT
);
CREATE INDEX idx_games_sport_date ON games (sport, game_date);

CREATE TABLE odds_snapshots (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id           TEXT NOT NULL,
    sport             TEXT NOT NULL,
    book              TEXT,
    market            TEXT,
    outcome_type      TEXT,
    line              DOUBLE PRECISION,
    price_american    INTEGER,
    price_decimal     DOUBLE PRECISION,
    snapshot_time_utc TEXT
);
CREATE INDEX idx_odds_snapshots_game_market_time
    ON odds_snapshots (game_id, market, snapshot_time_utc);
CREATE UNIQUE INDEX uq_odds_snapshots
    ON odds_snapshots (game_id, book, market, outcome_type, snapshot_time_utc);

CREATE TABLE features (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id    TEXT NOT NULL,
    sport      TEXT NOT NULL,
    as_of_date TEXT,
    key        TEXT,
    value      DOUBLE PRECISION,
    value_text TEXT
);
CREATE UNIQUE INDEX uq_features ON features (game_id, as_of_date, key);

CREATE TABLE recommendations (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_key                TEXT NOT NULL,
    sport                  TEXT NOT NULL,
    game_id                TEXT NOT NULL,
    generated_at_utc       TEXT,
    market                 TEXT,
    side                   TEXT,
    line                   DOUBLE PRECISION,
    target_price_american  INTEGER,
    fair_price_american    INTEGER,
    edge_percent           DOUBLE PRECISION,
    confidence             TEXT,
    units                  DOUBLE PRECISION,
    is_shadow              INTEGER DEFAULT 0,
    is_fade                INTEGER DEFAULT 0,
    num_books_in_consensus INTEGER,
    closing_price_american INTEGER,
    clv_percent            DOUBLE PRECISION,
    result                 TEXT,
    unit_profit            DOUBLE PRECISION,
    graded_at_utc          TEXT,
    model_probability      DOUBLE PRECISION,
    notes                  TEXT,
    config_version         TEXT
);
CREATE INDEX idx_rec_bot_sport ON recommendations (bot_key, sport);
CREATE INDEX idx_rec_game      ON recommendations (game_id);
CREATE INDEX idx_rec_result    ON recommendations (result);

CREATE TABLE bets (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport                  TEXT NOT NULL,
    game_id                TEXT,
    book                   TEXT,
    market                 TEXT,
    side                   TEXT,
    line                   DOUBLE PRECISION,
    price_american         INTEGER,
    units                  DOUBLE PRECISION,
    placed_at_utc          TEXT,
    recommendation_id      INTEGER,
    closing_price_american INTEGER,
    clv_percent            DOUBLE PRECISION,
    result                 TEXT,
    unit_profit            DOUBLE PRECISION,
    graded_at_utc          TEXT,
    notes                  TEXT
);
CREATE INDEX idx_bet_game   ON bets (game_id);
CREATE INDEX idx_bet_result ON bets (result);

CREATE TABLE results (
    game_id          TEXT PRIMARY KEY,
    sport            TEXT NOT NULL,
    detail_json      TEXT,
    home_final       INTEGER,
    away_final       INTEGER,
    status           TEXT,
    last_updated_utc TEXT
);

CREATE TABLE pulls (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pull_time_utc      TEXT,
    sport              TEXT,
    source             TEXT,
    requests_remaining INTEGER,
    requests_used      INTEGER,
    success            INTEGER,
    error              TEXT
);

CREATE TABLE settings (
    key            TEXT PRIMARY KEY,
    value          TEXT,
    updated_at_utc TEXT
);
