-- ============================================================================
-- schema_postgres.sql — Postgres (Neon) translation of the SQLite schema.
-- Generated from the LIVE SQLite schema (PRAGMA introspection), so column
-- order and every ALTER-added column match the source exactly.
--
-- SQLite -> Postgres mapping decisions:
--   INTEGER PRIMARY KEY AUTOINCREMENT  -> INTEGER GENERATED BY DEFAULT AS IDENTITY
--        (BY DEFAULT, not ALWAYS, so the migration can insert explicit ids;
--         sequence is reset to MAX(id) after load.)
--   REAL                               -> DOUBLE PRECISION
--   TEXT                               -> TEXT
--   INTEGER                            -> INTEGER (game_pk/ids well under int4 max)
--   Boolean-ish INTEGER columns (is_shadow, yrfi, f5_home_win, is_confirmed,
--        success) are kept as INTEGER on purpose — no BOOLEAN coercion.
--   Date/datetime values stay TEXT, byte-identical to SQLite (no reformatting).
--   NOT NULL / DEFAULT preserved exactly as the live SQLite schema reports them.
--
-- NOTE on personal_bets.recommendation_id: the SQLite schema has NO declared
-- foreign key (it is a plain INTEGER column). To faithfully mirror the source
-- this DDL also leaves it as a plain INTEGER — integrity is verified logically
-- in the verification gate, not enforced by a constraint. (Adding a real FK is
-- a deliberate schema change for a later stage, not this copy.)
-- ============================================================================

CREATE TABLE games (
    game_pk           INTEGER PRIMARY KEY,
    game_date         TEXT,
    game_datetime_utc TEXT,
    home_team         TEXT,
    away_team         TEXT,
    home_team_id      INTEGER,
    away_team_id      INTEGER,
    venue             TEXT,
    venue_id          INTEGER,
    status            TEXT,
    home_score        INTEGER,
    away_score        INTEGER,
    last_updated_utc  TEXT
);

CREATE TABLE probable_pitchers (
    game_pk          INTEGER,
    team_side        TEXT,
    pitcher_id       INTEGER,
    pitcher_name     TEXT,
    pitcher_throws   TEXT,
    is_confirmed     INTEGER DEFAULT 0,
    last_updated_utc TEXT,
    UNIQUE (game_pk, team_side)
);

CREATE TABLE odds_snapshots (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_pk             INTEGER,
    book                TEXT,
    market              TEXT,
    outcome_type        TEXT,
    line                DOUBLE PRECISION,
    price_american      INTEGER,
    price_decimal       DOUBLE PRECISION,
    snapshot_time_utc   TEXT,
    api_last_update_utc TEXT
);
CREATE INDEX idx_odds_snapshots_game_market_time
    ON odds_snapshots (game_pk, market, snapshot_time_utc);
CREATE UNIQUE INDEX uq_odds_snapshots
    ON odds_snapshots (game_pk, book, market, outcome_type, snapshot_time_utc);

CREATE TABLE recommendations (
    id                                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_pk                           INTEGER,
    generated_at_utc                  TEXT,
    market                            TEXT,
    side                              TEXT,
    line                              DOUBLE PRECISION,
    target_price_american             INTEGER,
    fair_price_american               INTEGER,
    edge_percent                      DOUBLE PRECISION,
    confidence_color                  TEXT,
    recommended_stake_pct             DOUBLE PRECISION,
    recommended_stake_dollars_at_2500 DOUBLE PRECISION,
    is_shadow                         INTEGER DEFAULT 0,
    closing_price_american            INTEGER,
    clv_percent                       DOUBLE PRECISION,
    result                            TEXT,
    result_payout_at_stake_1          DOUBLE PRECISION,
    graded_at_utc                     TEXT,
    num_books_in_consensus            INTEGER NOT NULL DEFAULT 0,
    algo                              TEXT NOT NULL DEFAULT 'devig',
    model_probability                 DOUBLE PRECISION,
    model_notes                       TEXT,
    unit_profit                       DOUBLE PRECISION,
    classification_version            TEXT DEFAULT 'v2'
);
CREATE INDEX idx_rec_game_pk      ON recommendations (game_pk);
CREATE INDEX idx_rec_generated_at ON recommendations (generated_at_utc);
CREATE INDEX idx_rec_color_market ON recommendations (confidence_color, market);
CREATE INDEX idx_rec_result       ON recommendations (result);
CREATE INDEX idx_rec_algo         ON recommendations (algo);

CREATE TABLE pitcher_stats (
    pitcher_id       INTEGER,
    season           TEXT,
    as_of_date       TEXT,
    ip               DOUBLE PRECISION,
    k_pct            DOUBLE PRECISION,
    bb_pct           DOUBLE PRECISION,
    hr_per_9         DOUBLE PRECISION,
    fip              DOUBLE PRECISION,
    era              DOUBLE PRECISION,
    throws           TEXT,
    last_updated_utc TEXT,
    UNIQUE (pitcher_id, as_of_date)
);
CREATE INDEX idx_ps_pitcher_date ON pitcher_stats (pitcher_id, as_of_date);

CREATE TABLE team_offense_stats (
    team_id          INTEGER,
    season           TEXT,
    as_of_date       TEXT,
    wrc_plus_proxy   DOUBLE PRECISION,
    runs_per_game    DOUBLE PRECISION,
    ops              DOUBLE PRECISION,
    vs_lhp_ops       DOUBLE PRECISION,
    vs_rhp_ops       DOUBLE PRECISION,
    last_updated_utc TEXT,
    UNIQUE (team_id, as_of_date)
);
CREATE INDEX idx_tos_team_date ON team_offense_stats (team_id, as_of_date);

CREATE TABLE park_factors (
    venue_id        INTEGER PRIMARY KEY,
    venue_name      TEXT,
    park_run_factor DOUBLE PRECISION NOT NULL DEFAULT 1.0
);

CREATE TABLE personal_bets (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_pk                INTEGER,
    placed_at_utc          TEXT,
    book                   TEXT,
    market                 TEXT,
    side                   TEXT,
    line                   DOUBLE PRECISION,
    actual_price_american  INTEGER,
    stake_dollars          DOUBLE PRECISION,
    recommendation_id      INTEGER,
    closing_price_american INTEGER,
    clv_percent            DOUBLE PRECISION,
    result                 TEXT,
    payout_dollars         DOUBLE PRECISION,
    profit_loss_dollars    DOUBLE PRECISION,
    graded_at_utc          TEXT,
    unit_stake             DOUBLE PRECISION,
    unit_profit            DOUBLE PRECISION
);
CREATE INDEX idx_bet_game_pk   ON personal_bets (game_pk);
CREATE INDEX idx_bet_placed_at ON personal_bets (placed_at_utc);
CREATE INDEX idx_bet_rec_id    ON personal_bets (recommendation_id);
CREATE INDEX idx_bet_result    ON personal_bets (result);

CREATE TABLE linescores (
    game_pk                INTEGER PRIMARY KEY,
    home_runs_by_inning    TEXT,
    away_runs_by_inning    TEXT,
    home_f5_runs           INTEGER,
    away_f5_runs           INTEGER,
    first_inning_home_runs INTEGER,
    first_inning_away_runs INTEGER,
    yrfi                   INTEGER,
    f5_total_runs          INTEGER,
    f5_home_win            INTEGER,
    status                 TEXT,
    last_updated_utc       TEXT
);

CREATE TABLE odds_pulls (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pull_time_utc      TEXT,
    endpoint           TEXT,
    games_returned     INTEGER,
    requests_remaining INTEGER,
    requests_used      INTEGER,
    success            INTEGER,
    error_message      TEXT
);

CREATE TABLE settings (
    key            TEXT PRIMARY KEY,
    value          TEXT,
    updated_at_utc TEXT
);
